// react/cives-orbis/src/ui/mapElements/CityInfo.tsx
import { CityChanneled } from "@/core/serialization/channel";
import { camera, Transform } from "@/renderer/camera";
import { ProgressBar } from "@/ui/components";
import { useEffect, useRef } from "react";
import styles from "./CitiesLayer.module.css";
import { getTileCoords } from "@/renderer/utils";
import { controls } from "@/renderer/controls";
import { mapUi } from "../mapUi";

type Props = {
  city: CityChanneled;
};

export function CityInfo({ city }: Props) {
  const elRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const subscription = camera.transform$.subscribe(transform);
    return () => subscription.unsubscribe();
  }, [camera]);

  useEffect(() => {
    if (!elRef.current) {
      return;
    }
    elRef.current.style.setProperty("--player-color", city.cssColor);
  }, []);

  function transform(t: Transform) {
    if (!elRef.current) {
      return;
    }

    const box = camera.tileBoundingBox;
    const tile = city.tile;
    if (
      tile.x >= box.xStart &&
      tile.x <= box.xEnd &&
      tile.y >= box.yStart &&
      tile.y <= box.yEnd
    ) {
      elRef.current.style.visibility = "visible";
    } else {
      elRef.current.style.visibility = "hidden";
      return;
    }

    const cityScale = Math.pow(t.scale / 70, 0.4);
    let [x, y] = getTileCoords(tile);
    [x, y] = camera.canvasToScreen(x + 0.5, y + 0.8);
    elRef.current.style.transform = `translate(${x}px, ${y}px) scale(${cityScale})`;
  }

  function getBody() {
    if (city.visibilityLevel === "basic") {
      return <div className={styles.simpleView}>{city.name}</div>;
    }

    return (
      <div>
        <ProgressBar
          className={styles.growth}
          progress={city.totalFood}
          nextProgress={city.totalFood + city.foodPerTurn}
          total={city.foodToGrow}
        >
          <span>{city.name}</span>
          <span>({city.turnsToGrow})</span>
        </ProgressBar>

        <ProgressBar
          className={styles.production}
          progress={city.totalProduction}
          nextProgress={city.totalProduction + city.productionPerTurn}
          total={city.productionRequired ?? 0}
        >
          <span>{city.productName}</span>
          <span>({city.turnsToProductionEnd})</span>
        </ProgressBar>
      </div>
    );
  }

  return (
    <div
      className={styles.city}
      ref={elRef}
      onClick={() => mapUi.selectCity(city.id)}
      onMouseDown={(e) => controls.onMouseDown(e.nativeEvent)}
      onMouseUp={() => controls.onMouseUp()}
      onMouseMove={(e) => controls.onMouseMove(e.nativeEvent)}
      onWheel={(e) => controls.onWheel(e.nativeEvent)}
      onContextMenu={(e) => e.preventDefault()}
    >
      <div className={styles.info}>
        <div className={styles.size}>{city.size}</div>
        {getBody()}
      </div>
    </div>
  );
}

// src/app/ui/cities-layer/city-info/city-info.component.ts
import {
  Component,
  OnInit,
  ChangeDetectionStrategy,
  Input,
  ChangeDetectorRef,
  OnDestroy,
  HostBinding,
  ElementRef,
} from "@angular/core";

import { Subject, merge } from "rxjs";
import { filter, takeUntil } from "rxjs/operators";

import { getTileCoords } from "src/app/renderer/utils";
import { Controls } from "src/app/controls";
import { MapUi } from "../../map-ui";
import { Camera } from "src/app/renderer/camera";
import { GameApi } from "src/app/api";
import { City } from "src/app/api/city";

@Component({
  selector: "app-city-info",
  templateUrl: "./city-info.component.html",
  styleUrls: ["./city-info.component.scss"],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CityInfoComponent implements OnInit, OnDestroy {
  private _city: City;

  ngUnsubscribe = new Subject<void>();

  constructor(
    private cdr: ChangeDetectorRef,
    private elementRef: ElementRef<HTMLElement>,
    private game: GameApi,
    private camera: Camera,
    public controls: Controls,
    private mapUi: MapUi,
  ) {}

  ngOnInit(): void {
    const el = this.elementRef.nativeElement;
    el.style.setProperty("--player-color", this.city.player.cssColor);

    const thisCity = this.game.state!.cityUpdated$.pipe(
      filter((c) => c.id === this.city.id),
    );

    merge(this.game.state!.turn$, thisCity)
      .pipe(takeUntil(this.ngUnsubscribe))
      .subscribe(() => this.cdr.markForCheck());
  }

  ngOnDestroy() {
    this.ngUnsubscribe.next();
    this.ngUnsubscribe.complete();
  }

  @Input() set city(city: City) {
    this._city = city;
  }
  get city() {
    return this._city;
  }

  @HostBinding("style.transform")
  get transform() {
    // FIXME: This migth lead to performance issues. It is calculated for every city every time camera transform changes.
    let scale = this.camera.transform$.value.scale;
    scale = Math.pow(scale / 70, 0.4);
    let [x, y] = getTileCoords(this.city.tile);
    [x, y] = this.camera.canvasToScreen(x + 0.5, y + 0.8);
    return `translate(${x}px, ${y}px) scale(${scale})`;
  }

  selectCity() {
    this.mapUi.selectCity(this.city);
  }

  onContextMenu(event: Event) {
    event.preventDefault();
  }
}

<div
  class="info"
  (click)="selectCity()"
  (click)="controls.onClick($event)"
  (mousedown)="controls.onMouseDown($event)"
  (mouseup)="controls.onMouseUp($event)"
  (mousemove)="controls.onMouseMove($event)"
  (wheel)="controls.onWheel($event)"
  (contextmenu)="onContextMenu($event)"
>
  <div class="size">{{ city.size }}</div>
  <div *ngIf="areDetailsVisible; else simpleViewTmpl">
    <app-progress-bar
      class="growth"
      [progress]="city.totalFood"
      [nextProgress]="city.totalFood + city.foodPerTurn"
      [total]="city.foodToGrow"
    >
      <span>{{ city.name }}</span>
      <span class="turns">({{ city.turnsToGrow | turns }})</span>
    </app-progress-bar>

    <app-progress-bar
      class="production"
      [progress]="city.totalProduction"
      [nextProgress]="city.totalProduction + city.productionPerTurn"
      [total]="city.productionRequired || 0"
    >
      <span>
        {{ city.productName }}
      </span>
      <span class="turns">({{ city.turnsToProductionEnd | turns }})</span>
    </app-progress-bar>
  </div>
</div>

<ng-template #simpleViewTmpl>
  <div class="simple-view">{{ city.name }}</div>
</ng-template>
