// src/app/game-canvas/game-canvas.component.ts
import {
  Component,
  ElementRef,
  ViewChild,
  AfterViewInit,
  HostListener,
} from "@angular/core";

import { Controls } from "../controls";
import { GameRenderer } from "../renderer/renderer";

@Component({
  selector: "app-game-canvas",
  templateUrl: "./game-canvas.component.html",
  styleUrls: ["./game-canvas.component.scss"],
})
export class GameCanvasComponent implements AfterViewInit {
  @ViewChild("canvas") canvas: ElementRef<HTMLCanvasElement>;

  constructor(public controls: Controls, private renderer: GameRenderer) {}

  ngAfterViewInit() {
    this.renderer.setCanvas(this.canvas.nativeElement);
  }

  onContextMenu(event: Event) {
    event.preventDefault();
  }

  @HostListener("window:resize", ["$event"])
  onResize(event: Event) {
    this.renderer.resize(window.innerWidth, window.innerHeight);
  }

  @HostListener("window:keydown", ["$event"])
  onKeyDown(event: KeyboardEvent) {
    this.controls.onKeyDown(event);
  }

  @HostListener("window:keyup", ["$event"])
  onKeyUp(event: KeyboardEvent) {
    this.controls.onKeyUp(event);
  }
}

<canvas
  #canvas
  (click)="controls.onClick($event)"
  (tap)="controls.onTap($event)"
  (mousedown)="controls.onMouseDown($event)"
  (mouseup)="controls.onMouseUp($event)"
  (mousemove)="controls.onMouseMove($event)"
  (wheel)="controls.onWheel($event)"
  (contextmenu)="onContextMenu($event)"
  (panStart)="controls.onPanStart($event)"
  (pan)="controls.onPan($event)"
  (panMove)="controls.onPanMove($event)"
  (pinchStart)="controls.onPinchStart($event)"
  (pinch)="controls.onPinch($event)"
  (pinchEnd)="controls.onPinchEnd($event)"
></canvas>

// src/ui/GameCanvas.tsx
import { camera } from "@/renderer/camera";
import { controls } from "@/renderer/controls";
import { renderer } from "@/renderer/renderer";
import { memo } from "react";
import { useEventListener } from "usehooks-ts";

function GameCanvas_() {
  useEventListener("keydown", (event) => controls.onKeyDown(event));

  useEventListener("resize", () => {
    renderer.resize(window.innerWidth, window.innerHeight);
    camera.refresh();
  });

  return (
    <canvas
      ref={(canvas) => {
        if (canvas) {
          renderer.setCanvas(canvas);
        }
      }}
      onClick={(e) => controls.onClick(e.nativeEvent)}
      onMouseDown={(e) => controls.onMouseDown(e.nativeEvent)}
      onMouseUp={() => controls.onMouseUp()}
      onMouseMove={(e) => controls.onMouseMove(e.nativeEvent)}
      onWheel={(e) => controls.onWheel(e.nativeEvent)}
      onContextMenu={(e) => e.preventDefault()}
    />
  );
}

export const GameCanvas = memo(GameCanvas_);
