// src/app/ui/player-yields/player-yields.component.ts
import { Component, OnInit } from "@angular/core";

import { GameApi } from "src/app/api";

@Component({
  selector: "app-player-yields",
  templateUrl: "./player-yields.component.html",
  styleUrls: ["./player-yields.component.scss"],
})
export class PlayerYieldsComponent implements OnInit {
  constructor(private game: GameApi) {}

  ngOnInit(): void {}

  get yields() {
    return this.game.state!.trackedPlayer.yields;
  }
}

<div class="public-works-color" [appTooltip]="publicWorksTooltipTmpl">
  Public works: {{ yields.total.publicWorks }} ({{
    yields.perTurn.publicWorks >= 0 ? "+" : ""
  }}{{ yields.perTurn.publicWorks }})
</div>

<ng-template #publicWorksTooltipTmpl>
  <div>From cities: {{ yields.income.publicWorks }}</div>
  <div>Improvements maintainance: {{ yields.costs.publicWorks }}</div>
  <div>Netto per turn: {{ yields.perTurn.publicWorks }}</div>
</ng-template>

// src/ui/PlayerYields.tsx
import { bridge } from "@/bridge";
import { useObservable } from "@/utils";
import { Tooltip } from "./components";

export function PlayerYields() {
  const yields = useObservable(bridge.player.yields$);

  if (!yields) {
    return null;
  }

  return (
    <div>
      <Tooltip
        content={
          <>
            <div>From cities: {yields.income.publicWorks}</div>
            <div>Improvements maintainance: {yields.costs.publicWorks}</div>
            <div>Netto per turn: {yields.perTurn.publicWorks}</div>
          </>
        }
      >
        Public works: {yields.total.publicWorks} (
        {yields.perTurn.publicWorks >= 0 ? "+" : ""}
        {yields.perTurn.publicWorks})
      </Tooltip>
    </div>
  );
}
