// react/cives-orbis/src/ui/mapElements/CitiesLayer.tsx
import { game } from "@/api";
import { City } from "@/api/city";
import { camera } from "@/renderer/camera";
import { useEffect, useRef, useState } from "react";
import { merge } from "rxjs";
import styles from "./CitiesLayer.module.css";
import { CityInfo } from "./CityInfo";

export function CitiesLayer() {
  const elRef = useRef<HTMLDivElement>(null);

  const [cities, setCities] = useState<City[]>([]);

  useEffect(() => {
    const subscription = merge(
      game.state!.citySpawned$,
      game.state!.cityDestroyed$,
      game.state!.tilesExplored$,
    ).subscribe(updateCities);

    updateCities();

    return () => subscription.unsubscribe();
  }, []);

  useEffect(() => {
    const subscription = camera.transform$.subscribe(transform);
    return () => subscription.unsubscribe();
  }, [camera]);

  function updateCities() {
    const player = game.state!.trackedPlayer;
    setCities(
      game.state!.cities.filter((city) => player.exploredTiles.has(city.tile)),
    );

    setTimeout(transform);
  }

  function transform() {
    if (!elRef.current) {
      return;
    }

    const t = camera.transform;

    let opacity = 1;
    if (t.scale < 30) {
      opacity = Math.max(0, 1 - (30 - t.scale) / 8);
    }
    elRef.current.style.opacity = opacity.toString();
  }

  return (
    <div ref={elRef} className={styles.citiesLayer}>
      {cities.map((city) => (
        <CityInfo key={city.id} city={city} />
      ))}
    </div>
  );
}

// src/app/ui/cities-layer/cities-layer.component.ts
import {
  Component,
  OnInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  HostBinding,
} from "@angular/core";

import { Subject, merge } from "rxjs";
import { takeUntil } from "rxjs/operators";

import { Camera } from "src/app/renderer/camera";
import { GameApi } from "src/app/api";
import { City } from "src/app/api/city";

@Component({
  selector: "app-cities-layer",
  templateUrl: "./cities-layer.component.html",
  styleUrls: ["./cities-layer.component.scss"],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CitiesLayerComponent implements OnInit {
  ngUnsubscribe = new Subject<void>();

  cities: City[];

  constructor(
    private cdr: ChangeDetectorRef,
    private game: GameApi,
    private camera: Camera,
  ) {}

  ngOnInit(): void {
    if (!this.game.state) {
      return;
    }

    merge(this.game.state.citySpawned$, this.game.state.cityDestroyed$)
      .pipe(takeUntil(this.ngUnsubscribe))
      .subscribe(() => {
        this.updateCities();
      });

    this.camera.transform$
      .pipe(takeUntil(this.ngUnsubscribe))
      .subscribe(() => this.cdr.markForCheck());

    this.game.stop$.subscribe(() => {
      this.cities = [];
      this.cdr.markForCheck();
    });

    this.updateCities();
  }

  ngOnDestroy() {
    this.ngUnsubscribe.next();
    this.ngUnsubscribe.complete();
  }

  updateCities() {
    const player = this.game.state!.trackedPlayer;
    this.cities = this.game.state!.cities.filter((city) =>
      player.exploredTiles.has(city.tile),
    );
    this.cdr.markForCheck();
  }

  trackByCityId(index: number, city: City) {
    return city.id;
  }

  @HostBinding("style.opacity")
  get opacity() {
    const scale = this.camera.transform$.value.scale;
    if (scale > 20) {
      return 1;
    }
    return Math.max(0, 1 - (20 - scale) / 8);
  }
}

<app-city-info
  *ngFor="let city of cities; trackBy: trackBycityId"
  [city]="city"
></app-city-info>
