// src/app/ui/widgets/multiselect/multiselect.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

import { Option } from "../option.interface";

@Component({
  selector: "app-multiselect",
  templateUrl: "./multiselect.component.html",
  styleUrls: ["./multiselect.component.scss"],
})
export class MultiselectComponent {
  @Input() options: Option[];

  @Input() value: any[];

  @Output() changed = new EventEmitter<any[]>();

  toggleOption(option: Option) {
    if (this.value.includes(option.value)) {
      const index = this.value.indexOf(option.value);
      const newValue = [...this.value];
      newValue.splice(index, 1);
      this.changed.next(newValue);
    } else {
      this.changed.next([...this.value, option.value]);
    }
  }
}

<div
  class="option"
  *ngFor="let option of options()"
  [class.selected]="value().includes(option.value)"
  (click)="toggleOption(option)"
>
  {{ option.label }}
</div>

// src/ui/components/Multiselect.tsx
import { Option } from "./types";
import styles from "./Radio.module.css";
import clsx from "clsx";

type Props<T> = {
  options: Option<T>[];
  value: T[];
  onChange: (value: T[]) => void;
};

export function Multiselect<T>({ options, value, onChange }: Props<T>) {
  function toggleOption(option: Option<T>) {
    if (value.includes(option.value)) {
      const index = value.indexOf(option.value);
      const newValue = [...value];
      newValue.splice(index, 1);
      onChange(newValue);
    } else {
      onChange([...value, option.value]);
    }
  }

  return (
    <div>
      {options.map((option, i) => (
        <div
          key={i}
          className={clsx(styles.option, {
            [styles.selected]: value.includes(option.value),
          })}
          onClick={() => toggleOption(option)}
        >
          {option.label}
        </div>
      ))}
    </div>
  );
}
