// react/cives-orbis/src/ui/UnitPanel.tsx
import { bridge } from "@/bridge";
import { UnitOrder } from "@/core/unit";
import { ACTIONS, UnitAction } from "@/core/unit-actions";
import { useForceRender, useObservable } from "@/utils";
import clsx from "clsx";
import { Panel } from "./components";
import { mapUi } from "./mapUi";
import styles from "./UnitPanel.module.css";

export function UnitPanel() {
  const unit = useObservable(mapUi.selectedUnit$);
  const combatSimulation = useObservable(mapUi.combatSimulation$);
  const forceRender = useForceRender();

  console.log(combatSimulation);

  function destroy() {}

  async function setOrder(order: UnitOrder) {
    if (!unit) {
      return;
    }
    await bridge.units.setOrder({ unitId: unit.id, order });
    forceRender();
  }

  async function doAction(action: UnitAction) {
    if (!unit) {
      return;
    }
    await bridge.units.doAction({ action, unitId: unit.id });
  }

  function getActionName(action: UnitAction) {
    return ACTIONS[action].name;
  }

  if (!unit) {
    return null;
  }

  function canDoAction(action: UnitAction) {
    return !!action;
  }

  return (
    <Panel corner="bottom-left">
      <div className="header">
        <h2>{unit.definition.name}</h2>
        {/* <app-unit #unitComponent [unit]="unitSimple"></app-unit> */}
      </div>
      <p>Moves: {unit.actionPointsLeft}</p>
      <p>Strength: {unit.definition.strength}</p>
      <p>Order: {unit.order}</p>
      <p>Health: {unit.health}</p>
      <p>Supplies: {unit.supplies}</p>
      {!unit.isSupplied && <p>Out of range of supply lines</p>}

      <div className={styles.actions}>
        <button className="btn-danger" onClick={destroy}>
          Disband
        </button>

        <button onClick={() => setOrder("skip")}>Skip move</button>

        <button onClick={() => setOrder("sleep")}>Sleep</button>
      </div>

      <div className={styles.actions}>
        {unit.definition.actions.map((action, i) => (
          <button
            key={i}
            className={clsx("btn", { disabled: !canDoAction(action) })}
            onClick={() => doAction(action)}
          >
            {getActionName(action)}
          </button>
        ))}
      </div>
    </Panel>
  );
}

// src/app/ui/unit-panel/unit-panel.component.ts
import { Component, OnInit, OnDestroy } from "@angular/core";

import { Subject } from "rxjs";
import { takeUntil } from "rxjs/operators";

import { Game } from "src/app/core/game";
import { Unit } from "src/app/core/unit";
import { UnitAction, ACTIONS } from "src/app/core/unit-actions";

@Component({
  selector: "app-unit-panel",
  templateUrl: "./unit-panel.component.html",
  styleUrls: ["./unit-panel.component.scss"],
})
export class UnitPanelComponent implements OnInit, OnDestroy {
  unit: Unit | null = null;

  private ngUnsubscribe = new Subject<void>();

  constructor(private game: Game) {}

  ngOnInit(): void {
    this.game.unitsManager.activeUnit$
      .pipe(takeUntil(this.ngUnsubscribe))
      .subscribe((unit) => (this.unit = unit));
  }

  ngOnDestroy() {
    this.ngUnsubscribe.next();
  }

  get unit$() {
    return this.game.unitsManager;
  }

  getActionName(action: UnitAction) {
    return ACTIONS[action].name;
  }
}

<div class="wrapper" *ngIf="unit &&unitSimple">
  <div>
    <app-combat-info
      class="panel panel-top-right-corner"
      *ngIf="enemy && combatSimulation"
      [attacker]="unit"
      [defender]="enemy"
      [simulation]="combatSimulation"
    ></app-combat-info>

    <div class="unit-panel panel panel-top-right-corner">
      <div class="header">
        <h2>{{ unit.definition.name }}</h2>
        <app-unit #unitComponent [unit]="unitSimple"></app-unit>
      </div>
      <p>Moves: {{ unit.actionPointsLeft }}</p>
      <p>Strength: {{ unit.definition.strength }}</p>
      <p>Order: {{ unit.order }}</p>
      <p>Health: {{ unit.health }}</p>
      <p>Supplies: {{ unit.supplies }}</p>
      <p *ngIf="!unit.isSupplied">Out of range of supply lines</p>

      <div class="actions">
        <button class="btn-danger" (click)="destroy()">Disband</button>

        <button (click)="setOrder('skip')">Skip move</button>

        <button (click)="setOrder('sleep')">Sleep</button>
      </div>

      <div class="actions">
        <button
          *ngFor="let action of unit.definition.actions"
          [class.disabled]="!unit.canDoAction(action)"
          [appTooltip]="unitActionsTooltipTmpl"
          [tooltipContext]="{ action: action }"
          (click)="unit.doAction(action)"
        >
          {{ getActionName(action) }}
        </button>
      </div>
    </div>
  </div>

  <app-tile-units
    *ngIf="unit.tile.units.length > 1"
    [tile]="unit.tile"
  ></app-tile-units>

  <ng-template #unitActionsTooltipTmpl let-action="action">
    <app-unit-action-requirements
      [unit]="unit"
      [action]="action"
    ></app-unit-action-requirements>
  </ng-template>
</div>

<app-unit-marker *ngIf="unit" [unit]="unit"></app-unit-marker>
