// src/app/ui/editor/tile-editor/tile-editor.component.ts
import { Component, OnInit, Input } from "@angular/core";

import { Observable } from "rxjs";
import { takeUntil, filter } from "rxjs/operators";

import { Game } from "src/app/core/game";
import { Tile, TileDirection } from "src/app/core/tile";
import {
  CLIMATE_OPTIONS,
  FOREST_OPTIONS,
  LAND_FORM_OPTIONS,
  RIVER_OPTIONS,
  SEA_LEVEL_OPTIONS,
  WETLANDS_OPTIONS,
} from "../constants";
import { OPPOSITE_DIRECTIONS } from "src/app/map-generators/utils";
import { isTileForestable, areWetlandsPossible } from "../utils";
import { MapUi } from "../../map-ui";

@Component({
  selector: "app-tile-editor",
  templateUrl: "./tile-editor.component.html",
  styleUrls: ["./tile-editor.component.scss"],
})
export class TileEditorComponent implements OnInit {
  @Input() isVisible$: Observable<boolean>;

  tile: Tile | null = null;

  SEA_LEVEL_OPTIONS = SEA_LEVEL_OPTIONS;
  LAND_FORM_OPTIONS = LAND_FORM_OPTIONS;
  CLIMATE_OPTIONS = CLIMATE_OPTIONS;
  FOREST_OPTIONS = FOREST_OPTIONS;
  RIVER_OPTIONS = RIVER_OPTIONS;
  WETLANDS_OPTIONS = WETLANDS_OPTIONS;

  constructor(private game: Game, private mapUi: MapUi) {}

  ngOnInit(): void {
    const shown = this.isVisible$.pipe(filter((v) => v));
    const hidden = this.isVisible$.pipe(filter((v) => !v));

    shown.subscribe(() => {
      this.mapUi.enableSelectingTile(true);
      this.mapUi.selectedTile$
        .pipe(takeUntil(hidden))
        .subscribe((tile) => (this.tile = tile));
    });

    hidden.subscribe(() => this.mapUi.enableSelectingTile(false));
  }

  update() {
    if (this.tile) {
      this.game.tilesManager.updateTile(this.tile);
    }
  }

  updateForest(forest: boolean) {
    if (this.tile) {
      this.tile.forest = forest && isTileForestable(this.tile);
      this.update();
    }
  }

  updateWetlands(wetlands: boolean) {
    if (this.tile) {
      this.tile.wetlands = wetlands && areWetlandsPossible(this.tile);
      this.update();
    }
  }

  updateRiver(riverParts: TileDirection[]) {
    if (!this.tile) {
      return;
    }

    this.tile.riverParts = riverParts;
    for (const neighbour of this.tile.neighbours) {
      const dir = this.tile.getDirectionTo(neighbour);
      const hasRiver = riverParts.includes(dir);
      const oppositeDir = OPPOSITE_DIRECTIONS[dir];
      const neighbourRiverParts = new Set(neighbour.riverParts);
      if (hasRiver) {
        neighbourRiverParts.add(oppositeDir);
      } else {
        neighbourRiverParts.delete(oppositeDir);
      }
      neighbour.riverParts = Array.from(neighbourRiverParts);
      this.game.tilesManager.updateTile(neighbour);
    }
    this.update();
  }
}

<div class="tile" *ngIf="tile; else selectTilePromptTmpl">
  <div>
    <h4>Sea level</h4>
    <app-radio
      [options]="SEA_LEVEL_OPTIONS"
      [value]="tile.seaLevel"
      (changed)="tile.seaLevel = $event; update()"
    ></app-radio>
  </div>

  <div>
    <h4>Land form</h4>
    <app-radio
      [options]="LAND_FORM_OPTIONS"
      [value]="tile.landForm"
      (changed)="tile.landForm = $event; update()"
    ></app-radio>
  </div>

  <div>
    <h4>Climate</h4>
    <app-radio
      [options]="CLIMATE_OPTIONS"
      [value]="tile.climate"
      (changed)="tile.climate = $event; update()"
    ></app-radio>
  </div>

  <div>
    <h4>Forest</h4>
    <app-radio
      [options]="FOREST_OPTIONS"
      [value]="tile.forest"
      (changed)="updateForest($event)"
    ></app-radio>
  </div>

  <div>
    <h4>Wetlands</h4>
    <app-radio
      [options]="WETLANDS_OPTIONS"
      [value]="tile.wetlands"
      (changed)="updateWetlands($event)"
    ></app-radio>
  </div>

  <div>
    <h4>River</h4>
    <app-multiselect
      [options]="RIVER_OPTIONS"
      [value]="tile.riverParts"
      (changed)="updateRiver($event)"
    ></app-multiselect>
  </div>

  <div>
    <h4>Improvement</h4>
    <app-radio
      [options]="IMPROVEMENT_OPTIONS"
      [value]="tile.improvement"
      (changed)="updateImprovement($event)"
    ></app-radio>
  </div>

  <div>
    <h4>Road</h4>
    <app-radio
      [options]="ROAD_OPTIONS"
      [value]="tile.road"
      (changed)="updateRoad($event)"
    ></app-radio>
  </div>

  <div>
    <h4>Resource</h4>
    <app-radio
      [options]="RESOURCE_OPTIONS"
      [value]="tile.resource?.id || null"
      (changed)="updateResource($event)"
    ></app-radio>
  </div>
</div>

<ng-template #selectTilePromptTmpl>
  Select the tile to edit.
</ng-template>

// react/cives-orbis/src/ui/editor/TileEditor.tsx
import { Multiselect, Radio } from "@/ui/components";
import styles from "./TileEditor.module.css";

import { bridge } from "@/bridge";
import { useObservable } from "@/utils";
import { useEffect } from "react";
import { mapUi } from "../mapUi";
import {
  CLIMATE_OPTIONS,
  FOREST_OPTIONS,
  IMPROVEMENT_OPTIONS,
  LAND_FORM_OPTIONS,
  RESOURCE_OPTIONS,
  RIVER_OPTIONS,
  ROAD_OPTIONS,
  SEA_LEVEL_OPTIONS,
  WETLANDS_OPTIONS,
} from "./constants";

export function TileEditor() {
  const tile = useObservable(mapUi.selectedTile$);

  useEffect(() => {
    mapUi.enableSelectingTile(true);
    return () => mapUi.enableSelectingTile(false);
  }, []);

  if (!tile) {
    return <div>Select the tile to edit</div>;
  }

  return (
    <div className={styles.tile}>
      <div>
        <h4>Sea level</h4>
        <Radio
          options={SEA_LEVEL_OPTIONS}
          value={tile.seaLevel}
          onChange={(seaLevel) =>
            bridge.tiles.update({ id: tile!.id, seaLevel })
          }
        />
      </div>

      <div>
        <h4>Land form</h4>
        <Radio
          options={LAND_FORM_OPTIONS}
          value={tile.landForm}
          onChange={(landForm) =>
            bridge.tiles.update({ id: tile!.id, landForm })
          }
        />
      </div>

      <div>
        <h4>Climate</h4>
        <Radio
          options={CLIMATE_OPTIONS}
          value={tile.climate}
          onChange={(climate) => bridge.tiles.update({ id: tile!.id, climate })}
        />
      </div>

      <div>
        <h4>Forest</h4>
        <Radio
          options={FOREST_OPTIONS}
          value={tile.forest}
          onChange={(forest) => bridge.tiles.update({ id: tile!.id, forest })}
        />
      </div>

      <div>
        <h4>Wetlands</h4>
        <Radio
          options={WETLANDS_OPTIONS}
          value={tile.wetlands}
          onChange={(wetlands) =>
            bridge.tiles.update({ id: tile!.id, wetlands })
          }
        />
      </div>

      <div>
        <h4>Improvements</h4>
        <Radio
          options={IMPROVEMENT_OPTIONS}
          value={tile.improvement}
          onChange={(improvement) =>
            bridge.tiles.update({ id: tile!.id, improvement })
          }
        />
      </div>

      <div>
        <h4>Road</h4>
        <Radio
          options={ROAD_OPTIONS}
          value={tile.road}
          onChange={(road) => bridge.tiles.update({ id: tile!.id, road })}
        />
      </div>

      <div>
        <h4>River</h4>
        <Multiselect
          options={RIVER_OPTIONS}
          value={tile.riverParts}
          onChange={(riverParts) =>
            bridge.tiles.update({ id: tile!.id, riverParts })
          }
        />
      </div>

      <div>
        <h4>Resource</h4>
        <Radio
          options={RESOURCE_OPTIONS}
          value={tile.resource?.id ?? null}
          onChange={(resourceId) =>
            bridge.tiles.setResource({
              tileId: tile!.id,
              resourceId,
              quantity: 1,
            })
          }
        />
      </div>
    </div>
  );
}
