// react/cives-orbis/src/ui/CombatInfo/CombatInfo.tsx
import { useObservable } from "@/utils";
import clsx from "clsx";
import { mapUi } from "../mapUi";
import { CombatInfoSide } from "./CombatInfoSide";

import { Panel } from "@/ui/components";
import styles from "./CombatInfo.module.css";

export function CombatInfo() {
  const combatSimulation = useObservable(mapUi.combatSimulation$);

  if (!combatSimulation) {
    return null;
  }

  const simulation = combatSimulation.simulation;

  const ratio = simulation.attacker.strength / simulation.defender.strength;

  function getResultClass(): string {
    if (ratio > 0.8 && ratio < 1.2) {
      return styles.even;
    }
    if (ratio > 1.2) {
      return styles.victory;
    }
    return styles.defeat;
  }

  function getResult(): string {
    if (ratio > 0.8 && ratio < 1.2) {
      return "even";
    }
    if (ratio > 1) {
      if (ratio > 2) {
        return "decisive victory";
      }
      if (ratio > 1.5) {
        return "major victory";
      }
      return "minor victory";
    }
    if (ratio < 0.4) {
      return "decisive defeat";
    }
    if (ratio < 0.7) {
      return "major defeat";
    }
    return "minor defeat";
  }

  return (
    <Panel className={styles.combatInfo}>
      <div className={styles.result}>
        <div className={clsx(styles.resultInner, getResultClass())}>
          {getResult()}
        </div>
      </div>

      <div className={styles.sides}>
        <CombatInfoSide
          label="Attacker"
          unitName={combatSimulation.attacker.definition.name}
          simulationSide={simulation.attacker}
        />

        <CombatInfoSide
          className={styles.invertedColors}
          label="Defender"
          unitName={combatSimulation.defender.definition.name}
          simulationSide={simulation.defender}
        />
      </div>
    </Panel>
  );
}

// src/app/ui/combat-info/combat-info.component.ts
import {
  Component,
  OnInit,
  Input,
  ChangeDetectionStrategy,
} from "@angular/core";

import { UnitDetails } from "src/app/api/unit-details";
import { Unit } from "src/app/api/unit";
import { CombatSimulation } from "src/app/core/combat";

@Component({
  selector: "app-combat-info",
  templateUrl: "./combat-info.component.html",
  styleUrls: ["./combat-info.component.scss"],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CombatInfoComponent implements OnInit {
  @Input() attacker: UnitDetails;

  @Input() defender: Unit;

  @Input() simulation: CombatSimulation;

  constructor() {}

  ngOnInit(): void {}

  get ratio() {
    return (
      this.simulation.attacker.strength / this.simulation.defender.strength
    );
  }

  get resultClass(): string {
    const ratio = this.ratio;
    if (ratio > 0.8 && ratio < 1.2) {
      return "even";
    }
    if (ratio > 1.2) {
      return "victory";
    }
    return "defeat";
  }

  get result(): string {
    const ratio = this.ratio;
    if (ratio > 0.8 && ratio < 1.2) {
      return "even";
    }
    if (ratio > 1) {
      if (ratio > 2) {
        return "decisive victory";
      }
      if (ratio > 1.5) {
        return "major victory";
      }
      return "minor victory";
    }
    if (ratio < 0.4) {
      return "decisive defeat";
    }
    if (ratio < 0.7) {
      return "major defeat";
    }
    return "minor defeat";
  }
}

<div class="result">
  <div class="result-inner {{ resultClass }}">{{ result }}</div>
</div>

<div class="sides">
  <app-combat-info-side
    label="Attacker"
    [unitName]="attacker.definition.name"
    [simulationSide]="simulation.attacker"
  ></app-combat-info-side>

  <app-combat-info-side
    label="Defender"
    class="inverted-colors"
    [unitName]="defender.definition.name"
    [simulationSide]="simulation.defender"
  ></app-combat-info-side>
</div>
