// react/cives-orbis/src/ui/CombatInfo/CombatInfoSide.tsx
import { CombatModifierType, CombatSimulationSide } from "@/core/combat";
import clsx from "clsx";
import styles from "./CombatInfo.module.css";

const MODIFIER_LABELS: Record<CombatModifierType, string> = {
  [CombatModifierType.river]: "from river",
  [CombatModifierType.hills]: "from hills",
  [CombatModifierType.health]: "from health penalty",
  [CombatModifierType.forest]: "from forest",
  [CombatModifierType.flanks]: "from flanks",
};

type Props = {
  label: string;
  unitName: string;
  simulationSide: CombatSimulationSide;
  className?: string;
};

export function CombatInfoSide({
  label,
  simulationSide,
  unitName,
  className,
}: Props) {
  return (
    <div className={clsx(styles.side, className)}>
      <h3 className={styles.sideName}>{label}</h3>
      <div>{unitName}</div>
      <div className={styles.field}>
        Approx. dmg.: <b>{simulationSide.damage}</b>
      </div>
      <div className={styles.field}>
        Strength: <b>{simulationSide.strength.toFixed(1)}</b>
      </div>

      <div>
        <div className={styles.modifier}>
          {simulationSide.modifiers.map((modifier) => (
            <div
              key={modifier.type}
              className={clsx(styles.modifier, {
                [styles.positive]: modifier.value > 0,
              })}
            >
              {modifier.value > 0 ? "+" : ""}
              {(modifier.value * 100).toFixed()}%
              {MODIFIER_LABELS[modifier.type]}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/app/ui/combat-info/combat-info-side/combat-info-side.component.ts
import { Component, OnInit, Input } from "@angular/core";

import { CombatSimulationSide, CombatModifierType } from "src/app/core/combat";

@Component({
  selector: "app-combat-info-side",
  templateUrl: "./combat-info-side.component.html",
  styleUrls: ["./combat-info-side.component.scss"],
})
export class CombatInfoSideComponent implements OnInit {
  MODIFIER_LABELS: Record<CombatModifierType, string> = {
    [CombatModifierType.river]: "from river",
    [CombatModifierType.hills]: "from hills",
    [CombatModifierType.health]: "from health penalty",
    [CombatModifierType.forest]: "from forest",
    [CombatModifierType.flanks]: "from flanks",
  };

  @Input() label: string;

  @Input() unitName: string;

  @Input() simulationSide: CombatSimulationSide;

  constructor() {}

  ngOnInit(): void {}
}

<h3>{{ label }}</h3>
<div>{{ unitName }}</div>
<div class="field">
  Approx. dmg.: <b>{{ simulationSide.damage }}</b>
</div>
<div class="field">
  Strength: <b>{{ simulationSide.strength.toFixed(1) }}</b>
</div>

<div class="modifiers">
  <div
    class="modifier"
    *ngFor="let modifier of simulationSide.modifiers"
    [class.positive]="modifier.value > 0"
  >
    {{ modifier.value > 0 ? "+" : "" }}{{ (modifier.value * 100).toFixed() }}%
    {{ MODIFIER_LABELS[modifier.type] }}
  </div>
</div>
