// react/cives-orbis/src/ui/gameMenu/SavesList.tsx
import { deleteSaveGame, exportSave, listSaveGames } from "@/api/saving";
import clsx from "clsx";
import { useEffect, useState } from "react";
import styles from "./GameMenu.module.css";

type Props = {
  selectedSave: string;
  onSelect: (save: string) => void;
};

export function SavesList({ selectedSave, onSelect }: Props) {
  const [saves, setSaves] = useState<string[]>([]);

  useEffect(refresh, []);

  function refresh() {
    setSaves(listSaveGames());
  }

  function _delete(save: string) {
    deleteSaveGame(save);
    refresh();
    if (selectedSave === save) {
      onSelect(save);
    }
  }

  if (!saves.length) {
    return <p>No saves yet</p>;
  }

  return saves.map((save) => (
    <div
      key={save}
      className={clsx(styles.save, {
        [styles.selected]: save === selectedSave,
      })}
      onClick={() => onSelect(save)}
    >
      <span>{save}</span>
      <div className={styles.saveActions}>
        <button onClick={() => exportSave(save)}>export</button>
        <button onClick={() => _delete(save)}>delete</button>
      </div>
    </div>
  ));
}

// src/app/ui/game-menu/saves-list/saves-list.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";

import { listSaveGames, deleteSaveGame, exportSave } from "../../../api/saving";

@Component({
  selector: "app-saves-list",
  templateUrl: "./saves-list.component.html",
  styleUrls: ["./saves-list.component.scss"],
})
export class SavesListComponent implements OnInit {
  @Input() selectedSave: string;

  @Output() change = new EventEmitter<string>();

  saves: string[];

  ngOnInit(): void {
    this.refresh();
  }

  delete(save: string) {
    deleteSaveGame(save);
    this.refresh();
    if (this.selectedSave === save) {
      this.change.next("");
    }
  }

  export(save: string) {
    exportSave(save);
  }

  refresh() {
    this.saves = listSaveGames();
  }
}

<div
  class="save"
  *ngFor="let save of saves"
  [class.selected]="save === selectedSave()"
  (click)="change.next(save)"
>
  <span>{{ save }}</span>
  <div class="save-actions">
    <button (click)="export(save)">export</button>
    <button (click)="delete(save)">delete</button>
  </div>
</div>

<div *ngIf="!saves.length">
  No saves yet
</div>
